### ISSUE TITLE
example data throws error

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/Heatmaps#11]
Hi @konnosif 

probably due to data but these commands all throw an error with the sample data :
```

 1883  python3 heat5.py --batch_files eg1_sepsis_minion/sample.txt --filter_sTF 0 --filter_sStart 0 --filter_sEnd 4 --suffix_label A --genus 1 --corr 0
 1884  python3 heat5.py --batch_files eg1_sepsis_minion/sample.txt --filter_sTF 0 --filter_sStart 0 --filter_sEnd 4 --suffix_label A --genus 0 --corr 0
 1885  python3 heat5.py --batch_files eg1_sepsis_minion/sample.txt --filter_sTF 0 --filter_sStart 0 --filter_sEnd 4 --genus 0 --corr 0
 1886  python3 heat5.py --batch_files eg1_sepsis_minion/sample.txt


Error 

python3 heat5.py --batch_files eg1_sepsis_minion/sample.txt
####Current directory is : /mnt/ngsnfs/tools/dev/Heatmaps
####Current file.txt with filenames to open is:eg1_sepsis_minion/sample.txt
Traceback (most recent call last):
  File "heat5.py", line 189, in <module>
    left3=left2.split("_")[0]+"_"+left2.split("_")[1]+"_"+left2.split("_")[2]
IndexError: list index out of range





```

**Comment by konnosif** [comment]
@colindaven i think i solved this. It's was a naming error of the sample files.

In most cases i had a set of files that where created from wochenende pipeline. If name files are different it might create errors. I hope not it's fixed.

 heap5.py should be updated and functional now.

**Comment by konnosif** [comment]
https://github.com/MHH-RCUG/Heatmaps/commit/666734f6a6e131c4dd6ac561d38b1b71bea79bf3  

Those changes should fix this.

**Comment by colindaven** [comment]
Hi Konstantinos, thanks for looking.

I'm still getting the same error, but my env might not be ok. Can you compare to yours ... ?

```
Error:
python3 heat5.py --batch_files eg1_sepsis_minion/sample.txt --filter_sTF 1 --filter_sStart 0 --filter_sEnd 4 --genus 1 --corr 0

####Current directory is : /mnt/ngsnfs/tools/dev/Heatmaps
####Current file.txt with filenames to open is:eg1_sepsis_minion/sample.txt
Traceback (most recent call last):
  File "heat5.py", line 189, in <module>
    left3=left2.split("_")[0]+"_"+left2.split("_")[1]+"_"+left2.split("_")[2]
IndexError: list index out of range
```


```
pip freeze
cycler==0.10.0
kiwisolver==1.1.0
matplotlib==3.0.3
numpy==1.18.3
pandas==0.24.2
pkg-resources==0.0.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
scipy==1.4.1
seaborn==0.9.1
six==1.14.0

```

**Comment by konnosif** [comment]
https://github.com/MHH-RCUG/Heatmaps/blob/master/heat5.py#L187


Line 189 is a command that is different in this version. Maybe i didn't manage to update it properly and you still run the old version.


Your error is : File "heat5.py", line 189, in <module>
    left3=left2.split("_")[0]+"_"+left2.split("_")[1]+"_"+left2.split("_")[2]
IndexError: list index out of range

But

left3=left2.split("_")[0]+"_"+left2.split("_")[1]+"_"+left2.split("_")[2] is into line 191 in the updated version.


I had the exactly same error you had into my environment too from day 1 so i fixed it but i am not if i uploaded properly.
___________________________________________________________
I used:

python3 heat5.py --batch_files sample.txt --filter_sTF 1 --filter_sStart 0 --filter_sEnd 4 --suffix_label A --genus 0 --corr 0                                 

['ERR2752909_R1', 'ERR2752910_R1', 'ERR2752911_R1', 'ERR2752912_R1', 'ERR2752913_R1', 'ERR2752914_R1', 'ERR2752915_R1', 'ERR2752916_R1', 'ERR2752918_R1']
                                                    ERR2752909_R1  ERR2752910_R1  ...  ERR2752918_R1     RowSum
1_CP001111_1_Stenotrophomonas_maltophilia_R551_...       6.022368       0.000000  ...       6.954196  40.532026
1_CP003583_1_Enterococcus_faecium_DO__complete_...       5.285402       8.625709  ...       0.000000  35.637366
1_CP001071_1_Akkermansia_muciniphila_ATCC_BAA_8...       0.000000       0.000000  ...       0.000000   5.392317
1_CP018420_1_Pseudomonas_veronii_strain_R02_chr...       0.000000       0.000000  ...       5.459432   5.459432
1_CP022048_2_Brevundimonas_vesicularis_strain_F...       0.000000       0.000000  ...       4.906891   4.906891
1_CP011602_1_Phytobacter_ursingii_strain_CAV115...       0.000000       0.000000  ...       4.807355   4.807355
1_AM181176_4_Pseudomonas_fluorescens_SBW25_comp...       0.000000       0.000000  ...       4.643856   4.643856
1_CP014546_1_Pseudomonas_azotoformans_strain_S4...       0.000000       0.000000  ...       4.584963   4.584963

[8 rows x 10 columns] AND
20  % Done
30  % Done
40  % Done
50  % Done
60  % Done
70  % Done
80  % Done
90  % Done
100 % DONE


________________________________________________________________________________

pip3 list --format freeze

asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
blinker==1.4
certifi==2018.1.18
chardet==3.0.4
click==6.7
cloud-init==19.4
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
cycler==0.10.0
distro-info==0.18ubuntu0.18.04.1
httplib2==0.9.2
hyperlink==17.3.1
idna==2.6
incremental==16.10.1
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.2.0
language-selector==0.1
MarkupSafe==1.0
matplotlib==3.2.1
netifaces==0.10.4
numpy==1.18.3
oauthlib==2.0.6
PAM==0.4.2
pandas==1.0.3
pip==9.0.1
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.5.3
pyOpenSSL==17.5.0
pyparsing==2.4.7
pyserial==3.4
python-apt==1.6.5+ubuntu0.2
python-dateutil==2.8.1
python-debian==0.1.32
pytz==2019.3
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
requests-unixsocket==0.1.5
scipy==1.4.1
seaborn==0.10.1
SecretStorage==2.3.1
service-identity==16.0.0
setuptools==39.0.1
six==1.14.0
ssh-import-id==5.7
systemd-python==234
Twisted==17.9.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
wheel==0.30.0
zope.interface==4.3.2
konstantinos@DESKTOP-US2IEGJ:/mnt/c/Users/konno/Desktop/Python$

**Comment by colindaven** [comment]
I think my git pull had failed or I didn't have the absolute most recent version. I tried again now after a pull and... it worked.

`eg1_sepsis_minion$ python3 heat5.py --batch_files sample.txt --filter_sTF 1 --filter_sStart 0 --filter_sEnd 4 --genus 1 --corr 0         `  

####Current directory is : /mnt/ngsnfs/tools/dev/Heatmaps/eg1_sepsis_minion
####Current file.txt with filenames to open is:sample.txt

Thanks Konstantinos
